berxel_camera_ros2:
    ros__parameters:
        base_frame_id : "berxel_base_link"
        camera_frame_id : "berxel_camera_link"
        depth_frame_id : "berxel_camera_depth_frame"
        ir_frame_id : "berxel_camera_ir_frame"
        color_frame_id : "berxel_camera_color_frame"
        depth_optical_frame_id : "berxel_camera_depth_optical_frame"
        ir_optical_frame_id : "berxel_camera_ir_optical_frame"
        color_optical_frame_id : "berxel_camera_color_optical_frame"

        camera_link_x : 0.0
        camera_link_y : 0.0152
        camera_link_z : 0.008155
        camera_link_roll : 0.0
        camera_link_pitch : 0.0
        camera_link_yaw : 0.0

        camera_rgb_frame_x : 0.006
        camera_rgb_frame_y : 0.0
        camera_rgb_frame_z : 0.0
        camera_rgb_frame_roll : 0.0
        camera_rgb_frame_pitch : 0.0
        camera_rgb_frame_yaw : 0.0

        camera_depth_frame_x : -0.004
        camera_depth_frame_y : 0.0
        camera_depth_frame_z : 0.0
        camera_depth_frame_roll : 0.0
        camera_depth_frame_pitch : 0.0
        camera_depth_frame_yaw : 0.0

        camera_rgb_optical_frame_x : 0.0
        camera_rgb_optical_frame_y : 0.0
        camera_rgb_optical_frame_z : 0.0
        camera_rgb_optical_frame_roll : -0.5
        camera_rgb_optical_frame_pitch : 0.0
        camera_rgb_optical_frame_yaw : -0.5

        camera_depth_optical_frame_x : 0.0
        camera_depth_optical_frame_y : 0.0
        camera_depth_optical_frame_z : 0.0
        camera_depth_optical_frame_roll : -0.5
        camera_depth_optical_frame_pitch : 0.0
        camera_depth_optical_frame_yaw : -0.5